<?php
/*******************************************************************************
 *  NAME: FontArray
 *  PARENT: FontManager
 *  DESCRIPTION: Array of fonts which can user use
 ******************************************************************************/

////////////////////////////////////////////////////////////////////////////////
// WHERE TO SET
////////////////////////////////////////////////////////////////////////////////
//size, family, weight, style, letterspacing
$heading_types = array(
    array('name'=> 'H1',
          'id' => 'headings_h1',
          'description' => 'hovno',
          'size'=>'12',
          'family'=>'Arial',
          'weight'=>'Italic',
          'style'=>'Normal',
          'letterspacing'=>'1',
          'disabled' => true,
          ),
    array('name'=> 'H2',
          'id' => 'headings_h2',
          'description' => 'hovno',
          'size'=>'12',
          'family'=>'Arial',
          'weight'=>'Italic',
          'style'=>'Normal',
          'letterspacing'=>'1',
          'disabled' => true,
          )
);
 
////////////////////////////////////////////////////////////////////////////////
// GOOGLE FONTS ARRAY
////////////////////////////////////////////////////////////////////////////////
$normal_fonts = array(	array('name' => "Cantarell", 'variant' => ':r,b,i,bi'),
						array('name' => "Cardo", 'variant' => ''),
						array('name' => "Crimson Text", 'variant' => '')
);
$google_fonts = array(	 "Cantarell",
						 "Cardo",
						 "Crimson Text",
						 "Droid Sans",
						 "Droid Sans Mono",
						 "Droid Serif",
						 "IM Fell DW Pica",
						 "Inconsolata",
						 "Josefin Sans Std Light",
						 "Josefin Slab",
						 "Lobster",
						 "Molengo",
						 "Nobile",
						 "OFL Sorts Mill Goudy TT",
						 "Old Standard TT",
						 "Reenie Beanie",
						 "Tangerine",
						 "Vollkorn",
						 "Yanone Kaffeesatz",
						 "Cuprum",
						 "Neucha",
						 "Neuton",
						 "PT Sans",
						 "Philosopher",
						 "Allerta",
						 "Allerta Stencil",
						 "Arimo",
						 "Arvo",
						 "Bentham",
						 "Coda",
						 "Cousine",
						 "Covered By Your Grace",
			 			 "Geo",
						 "Just Me Again Down Here",
						 "Puritan",
						 "Raleway",
						 "Tinos",
						 "UnifrakturCook",
						 "UnifrakturMaguntia",
						 "Mountains of Christmas",
						 "Lato",
						 "Orbitron",
						 "Allan",
						 "Anonymous Pro",
						 "Copse",
						 "Kenia",
						 "Ubuntu",
						 "Vibur",
						 "Sniglet",
						 "Syncopate",
						 "Cabin",
						 "Merriweather",
						 "Just Another Hand",
						 "Kristi",
						 "Corben",
						 "Gruppo",
						 "Buda",
						 "Lekton",
						 "Luckiest Guy",
						 "Crushed",
						 "Chewy",
						 "Coming Soon",
						 "Crafty Girls",
						 "Fontdiner Swanky",
						 "Permanent Marker",
						 "Rock Salt",
						 "Sunshiney",
						 "Unkempt",
						 "Calligraffitti",
						 "Cherry Cream Soda",
						 "Homemade Apple",
						 "Irish Growler",
						 "Kranky",
						 "Schoolbell",
						 "Slackey",
						 "Walter Turncoat",
						 "Radley",
						 "Meddon",
						 "Kreon",
						 "Dancing Script",
						 "Goudy Bookletter 1911",
						 "PT Serif Caption",
						 "PT Serif",
						 "Astloch"
);
?>